name: Run tests

on:
  workflow_dispatch:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ctsit/rstudio-ci:4.3.3

    env:
      CI: "TRUE"
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Install devtools
        run: Rscript -e 'install.packages("devtools")'

      - name: Install public R dependencies
        run: Rscript -e 'devtools::install_github("ctsit/redcapcustodian")'

      - uses: actions/checkout@v2

      - name: Check
        run: devtools::test(stop_on_failure = TRUE)
        shell: Rscript {0}
