name: Run tests

on:
  workflow_dispatch:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ctsit/rstudio-ci:4.1.0
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    env:
      CI: "TRUE"

    steps:
      - uses: actions/checkout@v2

      - name: Check
        run: devtools::test(stop_on_failure = TRUE)
        shell: Rscript {0}
