name: Run tests

on:
  workflow_dispatch:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ctsit/rstudio-ci:4.3.3
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    env:
      CI: "TRUE"
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      CR_PAT: ${{ secrets.CR_PAT }}

    steps:
      - name: Install devtools
        run: Rscript -e 'install.packages("devtools")'

      - name: Install public R dependencies
        run: Rscript -e 'devtools::install_github("ctsit/redcapcustodian")'

      - name: Install private R dependencies
        run: Rscript -e 'devtools::install_github("ctsit/rcc.ctsit")'

      - uses: actions/checkout@v2

      - name: Check
        run: devtools::test(stop_on_failure = TRUE)
        shell: Rscript {0}
